name: Demo worflow on actions
# This is a demo workflow ,Syntax allows to trigger on push , executing commands
on: [push]
    # schedule:
    #   - cron: "0/5 * * * *"
jobs:
    Run-Actions: ## job name
        runs-on: ubuntu-latest
        steps:
          - name: JavaScript actions
            id: greet ## used to reference the action
            uses: actions/hello-world-javascript-action@v1 #defining action
            with:
              who-to-greet: Vaishnavi #input
          - name: Printing Log actions
            run: |
             echo "Github Actions Name: ${GITHUB_ACTION}"
             echo "Github Action Path : ${GITHUB_ACTION_PATH}"
             echo "Github Action_Repository: ${GITHUB_ACTION_REPOSITORY}"
             echo "${{steps.greet.outputs.time}}"
    Run-Checkout-Actions: ## parallel jobs
        runs-on: ubuntu-latest
        steps:
            - name: Bash commands and Environment Variables ## Fetch commit id , repository name , current working directory in workflow
              run: |
                  pwd
                  ls
                  echo $GITHUB_SHA 
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_WORKSPACE 
                  echo "${{github.token}}"
              shell: bash
            - name: Execute checkout actions
              uses: actions/checkout@v3  ## checkout action definition.
            - name: Listing Files after checkout 
              run: |
                  pwd
                  ls
              shell: bash

            


        


