name: Container ## To see how we can run docker images inside github workflow
on: push
jobs:
    python_dockerimage:
        runs-on: ubuntu-latest
        container:
            image: python:3.11.0b3-alpine3.15 ## userid(inweblink):image
        steps:
          - name: Log Python version
            run: |
                python -v
                cat /etc/os-release

