name : Demo Worflow ## Name of the Workflow

on:
    push: 
        branches:
            - master 
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: Run a Shell Command
              run: echo "Hello World !!"
            - name: Multiline Command
              run: |
                  node -v 
                  npm -v 
