name: Github Workflows
### To see how other events trigger the workflow
on:  # by default runs on open synchoronized or repull requests
    pull_request:
      types: [closed, opened, assigned, reopen]
jobs:
    Run-Actions-on-Pullrequests:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger workflow on pull pull_request
              run : |
                  echo "Workflow triggered on Pull_Request"
              shell: bash

