name: Demo worflow

on: [push]
jobs:
    Run-bash-Command: ## job name
        runs-on: ubuntu-latest ## Setting Up a runner environment
        steps: ## steps to be exected
            - name: Bash command
              run: echo "Running bash scripts in ubuntu-latest environment in github server"
            - name: Print the present directory 
              run: pwd
              shell: bash
            - name: Python command
              run: |
                  import os 
                  print(os.listdir())
              shell: python
      
