name: Demo worflow
# This is a demo workflow ,Syntax allows to trigger on push , executing commands
on: [push]
jobs:
    Run-bash-Command: ## job name
        runs-on: ubuntu-latest ## Setting Up a runner environment
        steps: ## steps to be exected
            - name: Bash command
              run: echo "Running bash scripts in ubuntu-latest environment in github server"
            - name: Print the present directory 
              run: pwd
              shell: bash
            - name: Python command
              run: |
                  import os 
                  print(os.listdir())
              shell: python
    run-windows-command: ## 2nd job
        runs-on: windows-latest
        needs: [Run-bash-Command] ## To run jobs in series avoid to run in parallel.
        steps:
          - name: Running commands on Powershell
            run: mkdir Demo
            shell: pwsh
          - name: Going inside our directory
            run:  |
                cd Demo 
                dir 
            shell: cmd

      
