name: Workflow to understand Matrix and execute a python script
on: pull_request

jobs:
  matrix_jobs:
      strategy:
          matrix:
              os: [ubuntu-latest, windows_latest]
              py_version: ['2.x','3.x']
              exclude: ### To skip any of the matrix for any os version
                 -  py_version: '2.x'     
              include: ## To add any new variable to the matrix configuration . not like overwriting  
                  - os: ubuntu_latest
                    is_ubuntu: "true"
      runs-on: ${{matrix.os}}
      steps:
          - name: Python_Version
            run: python -v
          - name: To pull all scripts in github inside the workflow
            uses: actions/checkout@v3
          - name: To list contents in github
            run : ls 
          - name: Action to run Python_Script ## To run Python script 
            uses: actions/setup-python@v4
            with:
              python-version: ${{matrix.py_version}} ## input
              architecture: x64
          - run: python Scripts/sample.py 
          - name: print new ubuntu variable
            run: echo ${{matrix.is_ubuntu}}

